### ISSUE TITLE
Creating a new Quaternion

### ISSUE THREAD

**Issue by farzadmf** [kernan/vmath#11]
Hi, I'm trying to create a new `Quaternion` with the following code:

`Quaternion quat(Vector3(1, 1, 1), 45)`

But, it complains that I can't pass arguments to `Vector3`'s constructor. How can I create a `Vector3` then?

**Comment by kernan** [comment]
Can you please attach the full error and compiler version you're using?

**Comment by farzadmf** [comment]
Thank you for your reply,

I'm using Visual Studio 2015, and in my includes, I have the following:

```C++
#include <vmath/types.hpp>
#include <vmath/functions.hpp>
using vmath::Quaternion;
using vmath::Vector2;
using vmath::Vector3;
using vmath::Vector4;
using vmath::Matrix4x4;
```

And the error I get is _None of the overloads accepts 3 arguments_.

I was wondering if I miss an `include` or something else? Because when I look at the API pages, I don't seem to find the constructors for `Vector` (maybe I don't know where to search)

**Comment by kernan** [comment]
@farzadmf

https://msdn.microsoft.com/en-us/library/hh567368.aspx#corelanguagetable

Many features of this library rely on C++11 features that MSVC only partially supports. Until Microsoft implements inheriting constructors and expression SFINAE this library will not work with Visual Studio.

**Comment by kernan** [comment]
Further proof. The following works using both GCC 4.9 and Clang 3.5.
```
#include <iostream>

#include <vmath/types.hpp>
#include <vmath/functions.hpp>

using vmath::Quaternion;
using vmath::Vector2;
using vmath::Vector3;
using vmath::Vector4;
using vmath::Matrix4x4;

int main() {
        Quaternion quat(Vector3(1, 1, 1), 45);
        std::cout << "<" << quat.x << ", " << quat.y << ", " << quat.z << ", " << quat.w << ">" << std::endl;
}
```

```
rkernan@develop:~/workspace/vmath/issue_11$ g++ --version
g++ (Debian 4.9.2-10) 4.9.2
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

rkernan@develop:~/workspace/vmath/issue_11$ g++ -I/home/rkernan/workspace/vmath/inc -std=c++11 test.cpp -o test.gcc
rkernan@develop:~/workspace/vmath/issue_11$ ./test.gcc
<-0.28127, -0.28127, -0.28127, -0.873305>
```

**Comment by farzadmf** [comment]
So, there's no way to make it work? A hack or something?

**Comment by kernan** [comment]
No. Unless Microsoft implements these features in the MSVC compiler this library will not work.

**Comment by farzadmf** [comment]
OK, thank you for your help. Just as a suggestion, maybe it would not be a bad idea to update the README so that it mentions that it doesn't work on MSVC
